using System.Collections.Generic;
using System.Windows;
using Android.Views;

namespace Codon.UI.Elements.ValueConverters
{
	partial class BooleanToVisibilityConverterTests
	{
		Dictionary<ConvertParameters, ViewStates> expectedResultsDictionary
			= new Dictionary<ConvertParameters, ViewStates>
			{
				{new ConvertParameters(true, "Visible,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Visible,Gone"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Visible,Invisible"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Gone,Visible"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Gone,Gone"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Gone,Invisible"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Invisible,Visible"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Invisible,Gone"), ViewStates.Visible},
				{new ConvertParameters(true, "Visible,Invisible,Invisible"), ViewStates.Visible},
				{new ConvertParameters(true, "Gone,Visible,Visible"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Visible,Gone"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Visible,Invisible"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Gone,Visible"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Gone,Invisible"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Invisible,Visible"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Invisible,Gone"), ViewStates.Gone},
				{new ConvertParameters(true, "Gone,Invisible,Invisible"), ViewStates.Gone},
				{new ConvertParameters(true, "Invisible,Visible,Visible"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Visible,Gone"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Visible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Gone,Visible"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Gone,Gone"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Gone,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Invisible,Visible"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Invisible,Gone"), ViewStates.Invisible},
				{new ConvertParameters(true, "Invisible,Invisible,Invisible"), ViewStates.Invisible},

				{new ConvertParameters(false, "Visible,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(false, "Visible,Visible,Gone"), ViewStates.Visible},
				{new ConvertParameters(false, "Visible,Visible,Invisible"), ViewStates.Visible},
				{new ConvertParameters(false, "Visible,Gone,Visible"), ViewStates.Gone},
				{new ConvertParameters(false, "Visible,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(false, "Visible,Gone,Invisible"), ViewStates.Gone},
				{new ConvertParameters(false, "Visible,Invisible,Visible"), ViewStates.Invisible},
				{new ConvertParameters(false, "Visible,Invisible,Gone"), ViewStates.Invisible},
				{new ConvertParameters(false, "Visible,Invisible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(false, "Gone,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(false, "Gone,Visible,Gone"), ViewStates.Visible},
				{new ConvertParameters(false, "Gone,Visible,Invisible"), ViewStates.Visible},
				{new ConvertParameters(false, "Gone,Gone,Visible"), ViewStates.Gone},
				{new ConvertParameters(false, "Gone,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(false, "Gone,Gone,Invisible"), ViewStates.Gone},
				{new ConvertParameters(false, "Gone,Invisible,Visible"), ViewStates.Invisible},
				{new ConvertParameters(false, "Gone,Invisible,Gone"), ViewStates.Invisible},
				{new ConvertParameters(false, "Gone,Invisible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(false, "Invisible,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(false, "Invisible,Visible,Gone"), ViewStates.Visible},
				{new ConvertParameters(false, "Invisible,Visible,Invisible"), ViewStates.Visible},
				{new ConvertParameters(false, "Invisible,Gone,Visible"), ViewStates.Gone},
				{new ConvertParameters(false, "Invisible,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(false, "Invisible,Gone,Invisible"), ViewStates.Gone},
				{new ConvertParameters(false, "Invisible,Invisible,Visible"), ViewStates.Invisible},
				{new ConvertParameters(false, "Invisible,Invisible,Gone"), ViewStates.Invisible},
				{new ConvertParameters(false, "Invisible,Invisible,Invisible"), ViewStates.Invisible},

				{new ConvertParameters(null, "Visible,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Visible,Visible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Visible,Visible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Visible,Gone,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Visible,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Visible,Gone,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Visible,Invisible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Visible,Invisible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Visible,Invisible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Gone,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Gone,Visible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Gone,Visible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Gone,Gone,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Gone,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Gone,Gone,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Gone,Invisible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Gone,Invisible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Gone,Invisible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Invisible,Visible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Invisible,Visible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Invisible,Visible,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Invisible,Gone,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Invisible,Gone,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Invisible,Gone,Invisible"), ViewStates.Invisible},
				{new ConvertParameters(null, "Invisible,Invisible,Visible"), ViewStates.Visible},
				{new ConvertParameters(null, "Invisible,Invisible,Gone"), ViewStates.Gone},
				{new ConvertParameters(null, "Invisible,Invisible,Invisible"), ViewStates.Invisible},

			};
	}
}
