using System;
using System.Collections.Generic;
using System.Windows;

namespace Codon.UI.Elements.ValueConverters
{
	partial class BooleanToVisibilityConverterTests
	{
		Dictionary<ConvertParameters, Visibility> expectedResultsDictionary
			= new Dictionary<ConvertParameters, Visibility>
			{
				{new ConvertParameters(true, "Visible,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Visible,Collapsed"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Visible,Hidden"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Collapsed,Visible"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Collapsed,Collapsed"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Collapsed,Hidden"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Hidden,Visible"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Hidden,Collapsed"), Visibility.Visible},
				{new ConvertParameters(true, "Visible,Hidden,Hidden"), Visibility.Visible},
				{new ConvertParameters(true, "Collapsed,Visible,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Visible,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Visible,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Collapsed,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Hidden,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Collapsed,Hidden,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Visible,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Visible,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Visible,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Collapsed,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Hidden,Visible"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(true, "Hidden,Hidden,Hidden"), Visibility.Collapsed},

				{new ConvertParameters(false, "Visible,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(false, "Visible,Visible,Collapsed"), Visibility.Visible},
				{new ConvertParameters(false, "Visible,Visible,Hidden"), Visibility.Visible},
				{new ConvertParameters(false, "Visible,Collapsed,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Visible,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Visible,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(false, "Visible,Hidden,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Visible,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Visible,Hidden,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(false, "Collapsed,Visible,Collapsed"), Visibility.Visible},
				{new ConvertParameters(false, "Collapsed,Visible,Hidden"), Visibility.Visible},
				{new ConvertParameters(false, "Collapsed,Collapsed,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Hidden,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Collapsed,Hidden,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(false, "Hidden,Visible,Collapsed"), Visibility.Visible},
				{new ConvertParameters(false, "Hidden,Visible,Hidden"), Visibility.Visible},
				{new ConvertParameters(false, "Hidden,Collapsed,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Hidden,Visible"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(false, "Hidden,Hidden,Hidden"), Visibility.Collapsed},

				{new ConvertParameters(null, "Visible,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Visible,Visible,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Visible,Visible,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Visible,Collapsed,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Visible,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Visible,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Visible,Hidden,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Visible,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Visible,Hidden,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Collapsed,Visible,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Visible,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Collapsed,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Collapsed,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Hidden,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Collapsed,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Collapsed,Hidden,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Visible,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Hidden,Visible,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Visible,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Collapsed,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Hidden,Collapsed,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Collapsed,Hidden"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Hidden,Visible"), Visibility.Visible},
				{new ConvertParameters(null, "Hidden,Hidden,Collapsed"), Visibility.Collapsed},
				{new ConvertParameters(null, "Hidden,Hidden,Hidden"), Visibility.Collapsed},

			};
	}
}
