/*
<auto-generated>
	This file was generated by RequireArg.AreNotNull.tt.
</auto-generated>
*/

#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text;

namespace Calcium
{
	public static partial class RequireArg
	{
		/// <summary>
		/// Throws an exception if any of the specified values are null.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		[DebuggerStepThrough]
		public static void AreNotNull(
			[NotNull] object? arg1,
			[NotNull] object? arg2,
			[NotNull] object? arg3 = null,
			[NotNull] object? arg4 = null,
			[NotNull] object? arg5 = null,
			[NotNull] object? arg6 = null,
			[NotNull] object? arg7 = null,
			[NotNull] object? arg8 = null,
			[NotNull] object? arg9 = null,
			[NotNull] object? arg10 = null,
			[NotNull] object? arg11 = null,
			[NotNull] object? arg12 = null,
			[CallerArgumentExpression(nameof(arg1))]
			string? arg1Name = missingExpression,
			[CallerArgumentExpression(nameof(arg2))]
			string? arg2Name = missingExpression,
			[CallerArgumentExpression(nameof(arg3))]
			string? arg3Name = null,
			[CallerArgumentExpression(nameof(arg4))]
			string? arg4Name = null,
			[CallerArgumentExpression(nameof(arg5))]
			string? arg5Name = null,
			[CallerArgumentExpression(nameof(arg6))]
			string? arg6Name = null,
			[CallerArgumentExpression(nameof(arg7))]
			string? arg7Name = null,
			[CallerArgumentExpression(nameof(arg8))]
			string? arg8Name = null,
			[CallerArgumentExpression(nameof(arg9))]
			string? arg9Name = null,
			[CallerArgumentExpression(nameof(arg10))]
			string? arg10Name = null,
			[CallerArgumentExpression(nameof(arg11))]
			string? arg11Name = null,
			[CallerArgumentExpression(nameof(arg12))]
			string? arg12Name = null,

			[CallerMemberName] string? memberName = null,
			[CallerFilePath] string? filePath = null,
			[CallerLineNumber] int lineNumber = 0)
		{
			RequireParameterName(arg1Name, memberName, filePath, lineNumber);
			RequireParameterName(arg2Name, memberName, filePath, lineNumber);
			if (arg3Name != null)
			{
				RequireParameterName(arg3Name, memberName, filePath, lineNumber);
			}
			if (arg4Name != null)
			{
				RequireParameterName(arg4Name, memberName, filePath, lineNumber);
			}
			if (arg5Name != null)
			{
				RequireParameterName(arg5Name, memberName, filePath, lineNumber);
			}
			if (arg6Name != null)
			{
				RequireParameterName(arg6Name, memberName, filePath, lineNumber);
			}
			if (arg7Name != null)
			{
				RequireParameterName(arg7Name, memberName, filePath, lineNumber);
			}
			if (arg8Name != null)
			{
				RequireParameterName(arg8Name, memberName, filePath, lineNumber);
			}
			if (arg9Name != null)
			{
				RequireParameterName(arg9Name, memberName, filePath, lineNumber);
			}
			if (arg10Name != null)
			{
				RequireParameterName(arg10Name, memberName, filePath, lineNumber);
			}
			if (arg11Name != null)
			{
				RequireParameterName(arg11Name, memberName, filePath, lineNumber);
			}
			if (arg12Name != null)
			{
				RequireParameterName(arg12Name, memberName, filePath, lineNumber);
			}

			StringBuilder? nulls = null;

			AddNullArgumentName(ref nulls, arg1, arg1Name);
			AddNullArgumentName(ref nulls, arg2, arg2Name);
			if (arg3Name != null)
			{
				AddNullArgumentName(ref nulls, arg3, arg3Name);
			}
			if (arg4Name != null)
			{
				AddNullArgumentName(ref nulls, arg4, arg4Name);
			}
			if (arg5Name != null)
			{
				AddNullArgumentName(ref nulls, arg5, arg5Name);
			}
			if (arg6Name != null)
			{
				AddNullArgumentName(ref nulls, arg6, arg6Name);
			}
			if (arg7Name != null)
			{
				AddNullArgumentName(ref nulls, arg7, arg7Name);
			}
			if (arg8Name != null)
			{
				AddNullArgumentName(ref nulls, arg8, arg8Name);
			}
			if (arg9Name != null)
			{
				AddNullArgumentName(ref nulls, arg9, arg9Name);
			}
			if (arg10Name != null)
			{
				AddNullArgumentName(ref nulls, arg10, arg10Name);
			}
			if (arg11Name != null)
			{
				AddNullArgumentName(ref nulls, arg11, arg11Name);
			}
			if (arg12Name != null)
			{
				AddNullArgumentName(ref nulls, arg12, arg12Name);
			}

			if (nulls != null)
			{
				throw new ArgumentNullException(
					nulls.ToString(),
					"The arguments cannot be null. "
					+ FormatCallerParts(memberName, filePath, lineNumber));
			}
		}

		static void AddNullArgumentName(ref StringBuilder? nulls,
										object? value,
										string parameterName)
		{
			if (value != null)
			{
				return;
			}

			if (nulls == null)
			{
				nulls = new StringBuilder();
			}
			else
			{
				nulls.Append(", ");
			}

			nulls.Append(parameterName);
		}
	}
}